name: the_movie_db_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  drop_shadow: ^0.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
